version: '3'

networks:
  app-web:
   driver: bridge

services:
  mysql:
    image: mysql:5.7
    command: 
      --default-authentication-plugin=mysql_native_password 
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1 
    restart: always
    networks:
     - app-web
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=blog
    volumes:
     - ./mysql/data:/var/lib/mysql
     - ./mysql/my.cnf:/etc/my.cnf
    ports:
     - 3306:3306
  backend:
    image: backend-blog
    ports:
     - 5000:5000
    depends_on:
     - mysql
    networks:
     - app-web
  admin:
    image: admin-blog
    ports:
     - 4000:80
    depends_on:
     - backend
  frontend:
    image: frontend-blog
    ports:
     - 3000:3000
    depends_on:
     - backend
